---
- hosts: jetsonnanos
  remote_user: "{{ ansible_user }}"
  tasks:

  - name: Add realsense keys
    become: true
    apt_key:
      keyserver: keys.gnupg.net
      id: F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE

  - name: Add realsense apt repository
    become: true
    apt_repository:
      repo: deb http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic main
      state: present

  - name: Update apt sources
    become: true
    apt:
      update_cache: yes

  - name: Install robotont dependencies via apt
    apt:
      name: "{{ packages }}"
    become: true
    vars:
      packages:
        - ros-melodic-joy
        - ros-melodic-serial
        - ros-melodic-ddynamic-reconfigure
        - librealsense2-dev
        - screen
        - vim

  - name: Give user access to the serial port
    user:
      name: "{{ ansible_user }}"
      groups: dialout
      append: yes
    become: true


  - name: Clean up previous build
    file:
        path: "{{ item }}"
        state: absent
    with_items:
        - /home/{{ ansible_user }}/catkin_ws/build
        - /home/{{ ansible_user }}/catkin_ws/devel
        - /home/{{ ansible_user }}/catkin_ws/log

  - name: make Catkin folders
    file:
      path: "/home/{{ ansible_user }}/catkin_ws/src"
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: '0775'
    tags:
      - untested

  - name: Copy .rosinstall file with owner and permissions
    copy:
      src: resources/.rosinstall
      dest: /home/{{ ansible_user }}/catkin_ws/src/.rosinstall
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: '0644'

    #  - name: Clone robotont Git into Catkin workspace
    #    git:
    #      repo: https://github.com/ut-ims-robotics/robotont.git
    #      dest: /home/{{ ansible_user }}/catkin_ws/src
    #      version: kinetic-devel
    #    become_user: "{{ ansible_user }}"
    #    tags:
    #      - untested

  - name: Add ros default workspace to bashrc
    lineinfile:
      path: /home/{{ ansible_user }}/.bashrc
      line: source /opt/ros/melodic/setup.bash
    become_user: "{{ ansible_user }}"
    tags:
      - untested

  - name: Update catkin workspace
    shell: bash -ic 'wstool update -t src'
    args:
      chdir: /home/{{ ansible_user }}/catkin_ws
    tags: untested

  - name: fix /opt/ros/melodic/share/cv_bridge/cmake/cv_bridgeConfig.cmake to include opencv4 instead of opencv
    become: yes
    become_user: root
    replace:
      path: /opt/ros/melodic/share/cv_bridge/cmake/cv_bridgeConfig.cmake
      # The String to Search
      regexp: '\/usr\/include\/opencv'
      # The String to Replace
      replace: '/usr/include/opencv4'
  
  - name: Build Catkin workspace for robotont
    shell: bash -ic 'catkin build'
    args: 
      chdir: /home/{{ ansible_user }}/catkin_ws 
    tags: untested


    #  - name: Catkin Make with env loaded
    #    shell: |-
    #      source /home/{{ ansible_user }}/.bashrc
    #      catkin build
    #    become_user: "{{ ansible_user }}"
    #    args:
    #      executable: /bin/bash
    #      chdir: /home/{{ ansible_user }}/catkin_ws
    #    tags:
    #      - untested

  - name: Add catkin_ws to bashrc
    lineinfile:
      path: /home/{{ ansible_user }}/.bashrc
      line: source /home/{{ansible_user}}/catkin_ws/devel/setup.bash
    become_user: "{{ ansible_user }}"
    tags:
      - untested
